apiVersion: v1
kind: Service
metadata:
  name: {{ include "friendship-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer  # змініть це
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "friendship-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
